/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index.route";
import { Route as AccessSignupImport } from "./routes/access/signup";
import { Route as AccessSigninIndexImport } from "./routes/access/signin/index";

// Create/Update Routes

const IndexRouteRoute = IndexRouteImport.update({
	path: "/",
	getParentRoute: () => rootRoute,
} as any);

const AccessSignupRoute = AccessSignupImport.update({
	path: "/access/signup",
	getParentRoute: () => rootRoute,
} as any);

const AccessSigninIndexRoute = AccessSigninIndexImport.update({
	path: "/access/signin/",
	getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRoute;
		};
		"/access/signup": {
			preLoaderRoute: typeof AccessSignupImport;
			parentRoute: typeof rootRoute;
		};
		"/access/signin/": {
			preLoaderRoute: typeof AccessSigninIndexImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
	IndexRouteRoute,
	AccessSignupRoute,
	AccessSigninIndexRoute,
]);

/* prettier-ignore-end */
