/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index.route'

// Create Virtual Routes

const AccessSignupLazyImport = createFileRoute('/access/signup')()
const AccessSigninIndexLazyImport = createFileRoute('/access/signin/')()

// Create/Update Routes

const IndexRouteRoute = IndexRouteImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AccessSignupLazyRoute = AccessSignupLazyImport.update({
  path: '/access/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/access/signup.lazy').then((d) => d.Route))

const AccessSigninIndexLazyRoute = AccessSigninIndexLazyImport.update({
  path: '/access/signin/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/access/signin/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/access/signup': {
      preLoaderRoute: typeof AccessSignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/access/signin/': {
      preLoaderRoute: typeof AccessSigninIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRouteRoute,
  AccessSignupLazyRoute,
  AccessSigninIndexLazyRoute,
])

/* prettier-ignore-end */
